const constants = {
    ADD_NOTE: "ADD_NOTE",
    REMOVE_NOTE: "REMOVE_NOTE",
    UPDATE_NOTE: "UPDATE_NOTE",
    BEGIN_FETCH_NOTES :"BEGIN_FETCH_NOTES",
    FETCH_NOTES_SUCCESS :"FETCH_NOTES_SUCCESS",
    FETCH_NOTES_FAILURE :"FETCH_NOTES_FAILURE",
    MARK_NOTE: "MARK_NOTE",
    ADD_ERROR: "ADD_ERROR",
    CLEAR_ERROR: "CLEAR_ERROR"
  };
  
  export default constants;
  